[settings]
lockfile = true
minimum_release_age = "2d"
npm.package_manager = "auto"

[tools]
node = "lts"
pnpm = "12"

lefthook = "latest"
gitleaks = "latest"

claude = "latest"
"npm:@playwright/cli" = "latest"
"npm:ccusage" = "latest"


[hooks]
postinstall = "lefthook install"
